import type { Stock } from "./types";
/* Curated, liquid universe screened live. Kept ~32 names so a cold load stays within
   Finnhub's free-tier rate limit (2 calls/stock: metric + quote). Widen on a paid tier. */
export const UNIVERSE: Stock[] = [
  { sym:"AAPL",name:"Apple",sector:"Technology",tier:"L" },
  { sym:"MSFT",name:"Microsoft",sector:"Technology",tier:"L" },
  { sym:"NVDA",name:"NVIDIA",sector:"Technology",tier:"L" },
  { sym:"AMD",name:"Advanced Micro Devices",sector:"Technology",tier:"L" },
  { sym:"MU",name:"Micron Technology",sector:"Technology",tier:"L" },
  { sym:"SNDK",name:"SanDisk",sector:"Technology",tier:"L" },
  { sym:"INTC",name:"Intel",sector:"Technology",tier:"L" },
  { sym:"DELL",name:"Dell Technologies",sector:"Technology",tier:"L" },
  { sym:"INTU",name:"Intuit",sector:"Technology",tier:"L" },
  { sym:"FSLY",name:"Fastly",sector:"Technology",tier:"S" },
  { sym:"GOOGL",name:"Alphabet",sector:"Communication",tier:"L" },
  { sym:"META",name:"Meta Platforms",sector:"Communication",tier:"L" },
  { sym:"NFLX",name:"Netflix",sector:"Communication",tier:"L" },
  { sym:"ROKU",name:"Roku",sector:"Communication",tier:"M" },
  { sym:"AMZN",name:"Amazon",sector:"Consumer & Retail",tier:"L" },
  { sym:"TSLA",name:"Tesla",sector:"Consumer & Retail",tier:"L" },
  { sym:"COST",name:"Costco",sector:"Consumer & Retail",tier:"L" },
  { sym:"LULU",name:"Lululemon",sector:"Consumer & Retail",tier:"L" },
  { sym:"JPM",name:"JPMorgan Chase",sector:"Financials",tier:"L" },
  { sym:"V",name:"Visa",sector:"Financials",tier:"L" },
  { sym:"GS",name:"Goldman Sachs",sector:"Financials",tier:"L" },
  { sym:"SOFI",name:"SoFi Technologies",sector:"Financials",tier:"M" },
  { sym:"UNH",name:"UnitedHealth",sector:"Healthcare",tier:"L" },
  { sym:"LLY",name:"Eli Lilly",sector:"Healthcare",tier:"L" },
  { sym:"BSX",name:"Boston Scientific",sector:"Healthcare",tier:"L" },
  { sym:"HIMS",name:"Hims & Hers",sector:"Healthcare",tier:"M" },
  { sym:"CAT",name:"Caterpillar",sector:"Industrials",tier:"L" },
  { sym:"GE",name:"GE Aerospace",sector:"Industrials",tier:"L" },
  { sym:"BW",name:"Babcock & Wilcox",sector:"Industrials",tier:"S" },
  { sym:"XOM",name:"Exxon Mobil",sector:"Energy",tier:"L" },
  { sym:"SLB",name:"Schlumberger",sector:"Energy",tier:"L" },
  { sym:"KOS",name:"Kosmos Energy",sector:"Energy",tier:"M" },
];
